### ISSUE TITLE
Go to definition twice causes error

### ISSUE THREAD

**Issue by erietz-werner** [Decodetalkers/csharpls-extended-lsp.nvim#1]
If I go to definition once, it correctly goes to the definition. If I return to the original buffer where I came from via `<c-o>` or `<c-6>` and try to go to definition again I get this error

```
Error executing vim.schedule lua callback: ...harpls-extended-lsp.nvim/lua/csharpls_extended/utils.lua:50: Failed to rename buffer
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...harpls-extended-lsp.nvim/lua/csharpls_extended/utils.lua:50: in function 'get_or_create_buf'
        ...art\csharpls-extended-lsp.nvim/lua/csharpls_extended.lua:51: in function 'buf_from_metadata'
        ...art\csharpls-extended-lsp.nvim/lua/csharpls_extended.lua:103: in function 'get_metadata'
        ...art\csharpls-extended-lsp.nvim/lua/csharpls_extended.lua:128: in function 'handle_locations'
        ...art\csharpls-extended-lsp.nvim/lua/csharpls_extended.lua:147: in function 'handler'
        ...ols\neovim\nvim-win64\share\nvim\runtime/lua/vim/lsp.lua:1025: in function 'cb'
        vim/_editor.lua:256: in function <vim/_editor.lua:256>
```

This error does not occur if
1. When I am at the definition (aka the buffer named "netstandard")
2. I delete the buffer using `:bdelete`
3. Return to the previous file with `<c-o>`
4. Hit `gd` again to go back to the definition.

---

I am on `NVIM v0.7.0` on windows (unfortunately) with native lsp . This occurs in both git bash and powershell. Here is my lsp config

```lua
lspconfig['csharp_ls'].setup({
    on_attach = on_attach,
    capabilities = capabilities,
    handlers = {
        ["textDocument/definition"] = require("csharpls_extended").handler,
    },
})
```

My `on_attach` function has `gd` mapped to `vim.lsp.buf.definition` for the local buffer.

I have not debugged this issue and have not taken the time to understand how this plugin works exactly.

**Comment by Decodetalkers** [comment]
Can you upload a video, I cannot make this bug occur

**Comment by erietz-werner** [comment]
Here I have tested out the bug again on a minimal example. In the video I try to go to the definition of `Console` and the issue occurs.

https://user-images.githubusercontent.com/83087786/178743809-51fa251b-ee1a-4f8b-bd3c-27a3c4cd6642.mp4

I initially tried to go to the definition of `WriteLine` and it threw the same error immediately. However, it did create a buffer named System.Console that had the source bit it did not navigate there.

Let me know if there is any other info I can provide.

**Comment by Decodetalkers** [comment]
> https://github.com/Decodetalkers/csharpls-extended-lsp.nvim/blob/a1985fd1cd3c67d5e1b1be7c9283222fd46e7615/lua/csharpls_extended/utils.lua#L36
> 
> Maybe it has something to do with the buffer being named `C:\System.Console`? I have no idea though haha.

![image](https://user-images.githubusercontent.com/60290287/178872549-20d5d493-e33d-4916-a490-7998cbcf76ce.png)

This line ,change the name to "/System.Console", and retry jump to Console,

**Comment by Decodetalkers** [comment]
And add vim.notify(name), to see what the name is

**Comment by Decodetalkers** [comment]
Why C:\Program.Console...
