### ISSUE TITLE
Error during decompilation attempt

### ISSUE THREAD

**Issue by steeldebil** [Decodetalkers/csharpls-extended-lsp.nvim#6]
Go to definition works fine on files that don't need to be decompiled, but it doesn't work on files that need to be decompiled. This is probably due to the fact that I don't have ILSpy on the machine. How should I install and configure ILSpy if I'm running on manjaro linux?

Here is the error I get:
![image](https://github.com/Decodetalkers/csharpls-extended-lsp.nvim/assets/86685532/43b5edf7-5fb9-454b-b43a-b41eb52a03d1)

neovim version is 0.9.2, the plugin version is master branch, my [config](https://github.com/steeldebil/dotfiles/tree/laptop/.config/nvim)

**Comment by Decodetalkers** [comment]
Can you provide a min code for me to debug? thanks

**Comment by steeldebil** [comment]
After a few hours of playing around, I was able to figure out that this error was caused by using LazyVim (some of the many plugins that come with it) and when using minimal config (lazy.nvim, lspconfig, csharp-ls and your plugin) this error does not appear.

Sorry for the inconvenience

**Comment by Dantali0n** [comment]
Hello @molostovvs could you clarify which plugin is causing issues. I am using kickstart neovim and am having this same problem.

**Comment by molostovvs** [comment]
Hi. I switched to [roslyn lsp](https://github.com/seblj/roslyn.nvim) and I recommend it to you too. It uses the lsp from vscode c# extension, which is the best lsp for c# at the moment.
