### ISSUE TITLE
Doesn't work with telescope

### ISSUE THREAD

**Issue by searleser97** [Decodetalkers/csharpls-extended-lsp.nvim#7]
This plugin works correctly when we are not using Telescope to list definitions, but it throws an error when we try to use telescope 

![image](https://github.com/Decodetalkers/csharpls-extended-lsp.nvim/assets/5056411/ec5363da-7c61-4c88-ab7e-4160c437475f)

```
Error executing vim.schedule lua callback: ...-nightly/current/share/nvim/runtime/lua/vim/lsp/util.lua:1198: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...-nightly/current/share/nvim/runtime/lua/vim/lsp/util.lua:1198: in function 'jump_to_location'
        ...anc/forks/telescope.nvim/lua/telescope/builtin/__lsp.lua:210: in function 'handler'
        ...eovim-nightly/current/share/nvim/runtime/lua/vim/lsp.lua:1502: in function 'cb'
        vim/_editor.lua:324: in function <vim/_editor.lua:323>
```

**Comment by Decodetalkers** [comment]
sorry for have view this issue for so long time. I will take a view recently.. sorry for that

**Comment by Spycemyster** [comment]
Is this when looking up class definitions for source-generated classes? I'm getting this issue too on Godot C# scripts when I try to go to a partial class.

**Comment by Decodetalkers** [comment]
I think it is telescope's problem

https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/__lsp.lua#L131-L149

it request data directly from neovim, do not from the handlers by nvim-lspconfig.. maybe, it never request from me

**Comment by Decodetalkers** [comment]
find the code in neovim
```lua
local function request_with_options(name, params, options)
  local req_handler
  if options then
    req_handler = function(err, result, ctx, config)
      local client = vim.lsp.get_client_by_id(ctx.client_id)
      local handler = client.handlers[name] or vim.lsp.handlers[name]
      handler(err, result, ctx, vim.tbl_extend('force', config or {}, options))
    end
  end
  request(name, params, req_handler)
end
```

all right, the pr is mime

**Comment by Decodetalkers** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/2770/files

it is the problem of telescope, and there is already a pr for it

**Comment by Spycemyster** [comment]
It seems the issue has to do with multiple values being returned when finding a C# partial class that has other source-generated classes. I created a temporary fix for "go to definition" that just chooses the first value returned here https://github.com/Spycemyster/dotnet-goto.nvim

**Comment by Decodetalkers** [comment]
I have add support for telescope now, but a very basic one, I think I have solved it

**Comment by Decodetalkers** [comment]
Now telescope is supported, please take a look at README.md
